### ISSUE TITLE
High Sierra (10.13.3) Kernel Panic while changing many files

### ISSUE THREAD

**Issue by asottile** [mhallin/notify-forwarder#4]
Figure this is probably an apple issue and perhaps a bit of a shot in the dark.

I'm using `notify-forwarder` via https://github.com/mhallin/vagrant-notify-forwarder

My specific usecase involves a linux guest (ubuntu 14.04) though I don't think the guest matters all that much beyond "it's linux".

The host:

```console
$ uname -a
Darwin Macbook-Pro 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,4 Darwin
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.13.3 (17D47)
      Kernel Version: Darwin 17.4.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: asottile-mbp142
      User Name: Anthony Sottile (asottile)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1 day 5:25
```

The "large number of files" in question involves removing a shared `node_modules` folder from either the host or the guest (it is _much_ more likely to reproduce when deleted on the host, though it has also reproduced while deleting on the guest). (`rm -rf node_modules`)

The kernel panic in question ends with:

```
*** Panic Report ***
panic(cpu 7 caller 0xffffff800b6869f1): "vnode_dropiocount(0xffffff80607863e0): v_iocount < 1"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-4570.41.2/bsd/vfs/vfs_subr.c:4782
```

The `Vagrantfile` in question is part of a closed source application though it's pretty simple.  Let me know if you'd like additional information for reproducing this and I can attempt to anonymize it.

**Comment by mhallin** [comment]
Uh oh.

This seems like a bug on Apple's side - maybe something introduced with APFS? Have you filed a bug [in their tracker](https://bugreport.apple.com/web/)? If I could reproduce this crash I could also file one.

**Comment by asottile** [comment]
I have not filed a bug report yet (unfortunately) -- @elado could you file a report for me?

**Comment by asottile** [comment]
@mhallin interestingly enough, we're not seeing the same panic through https://github.com/adrienkohlbecker/vagrant-fsnotify

The two use a similar strategy so I wonder what's different and whether we can apply those fixes here :) (as your plugin seems to actually still have someone at the wheel, and the interface is better)

**Comment by asottile** [comment]
Looking at the difference in implementation:

- `notify-forwarder` uses [`utimes(...)`](https://linux.die.net/man/2/utimes) where as `fsnotify` uses `touch -a`
    - this means `notify-forwarder` updates both `mtime` and `atime`
- `fsnotify` debounces notifications
    - this seems to be the most promising difference? how does `notify-forwarder` handle events triggered as part of the `utime` update?  does a fs event even get triggered based on a utime update (I'll do some more research into this)

**Comment by asottile** [comment]
For testing a "noop receiver", I'm using `nc -u -l 9111` on the host (essentially a printing blackhole udp server) -- might be useful if anyone else wants to reproduce anything else I find :)

**Comment by asottile** [comment]
So I'm incorrect about notify-forwarder and debouncing.  It seems this parameter does debouncing for us: https://github.com/mhallin/notify-forwarder/blob/a25b32a364a9f040a8ea0f3e0dbeb9356e312e44/src/watch_fsevents.cc#L58

So the difference there is `fsnotify`'s debounce is 2 seconds (and in software?) and `notify-forwarder`'s is part of the kernel?

**Comment by asottile** [comment]
Seems the underlying gem in `fsnotify` uses the same fsevents call with `latency` set to `0.1` as well -- and then additionally does deduplication in ruby?  That seems to be the only functional different I can find so far -- I'll see if I can make the panics go away by increasing the latency (though I imagine that's just making them rarer?)

**Comment by asottile** [comment]
@mhallin here's a reproduction that reproduces for me pretty consistently:

### vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "private_network", ip: "192.168.50.9", :adapter => 2

  config.vm.provider "virtualbox" do |v|

    config.vm.synced_folder 'code', '/code', nfs: true

    # nat network
    v.customize ["modifyvm", :id, "--cableconnected1", "on"]
    v.customize ["modifyvm", :id, "--nictype1", "Am79C973"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    v.customize ["modifyvm", :id, "--nicpromisc1", "allow-all"]
    # host only network
    v.customize ["modifyvm", :id, "--cableconnected2", "on"]
    v.customize ["modifyvm", :id, "--nictype2", "Am79C973"]
    v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]

  end

  config.notify_forwarder.enable = true
end
```

### setup

```
mkdir -p code
vagrant up
```

### boom

I was able to get it to splode by doing the following (on the host)

```
cd code
git clone --depth 1 https://github.com/npm/npm  # some project with lots of deps
cd npm
npm install  # I installed npm from `brew`
rm -rf node_modules
```

Occasionally you need to do this a bit more:

```
npm install && rm -rf node_modules
```

It usually panics for me within ~2 iterations

**Comment by asottile** [comment]
I've opened a bug report with apple including the reproduction above.  Unfortunately bug reports are private so sharing the link here is fruitless.

**Comment by RReverser** [comment]
My Mac kept crashing randomly recently, and only today I decided to search by the error message and this was the first hit and indeed I started using this plugin recently... has anyone filed a bug to Apple yet as discussed above?

**Comment by asottile** [comment]
Just to circle back here, apple closed the issue and it appears fixed in Mojave!
